### ISSUE TITLE
Pub LotoQuébec pour le Riverain

### ISSUE THREAD

**Issue by SimonLabbe** [Linkupdated/Calypso#13]
Il faut mettre ce lien sur l'image

http://loteries-video.loto-quebec.com/fr?utm_source=detaillant&utm_medium=banner&utm_campaign=slvq

**Comment by Linkupdated** [comment]
ou ca l'image je ne la voit pas sur le site?

**Comment by SimonLabbe** [comment]
Tu as un interface dans un courriel avec l'image que tu dois insérer sur le site

Envoyé depuis un mobile

<div>-------- Message d'origine --------</div><div>De : Linkupdated notifications@github.com </div><div>Date :16/04/2015  23:12  (GMT-05:00) </div><div>À : Linkupdated/Calypso Calypso@noreply.github.com </div><div>Cc : SimonLabbe simon@labbe.ca </div><div>Objet : Re: [Calypso] Pub LotoQuébec pour le Riverain (#13) </div><div>
</div>ou ca l'image je ne la voit pas sur le site?

**Comment by Linkupdated** [comment]
C'est fait!

**Comment by SimonLabbe** [comment]
Mettre le "Salon VIP - 18 ans et plus." juste au dessus de la pub rouge et l'aligner à droite.
Ligne 495 dans index.php

**Comment by Linkupdated** [comment]
c'est fait, .25h
