### ISSUE TITLE
Calendrier au mois et fin d'inscription

### ISSUE THREAD

**Issue by SimonLabbe** [Linkupdated/Calypso#15]

**Comment by Linkupdated** [comment]
_à faire de nuit, vu que ça risque de faire tomber des sites down_

**Comment by Linkupdated** [comment]
4H  CLD acton   changer le calendrier et ajouter les inscriptions terminées

**Comment by SimonLabbe** [comment]
Aranger le bug lorceque l'on change de mois!

**Comment by Linkupdated** [comment]
regler!
