### ISSUE TITLE
Moteur de recherche produits

### ISSUE THREAD

**Issue by SimonLabbe** [Linkupdated/Calypso#16]

**Comment by Linkupdated** [comment]
#### Quelques questions
- y'a t'il un visuel ou je doit me debrouiller?
- c'est quoi les champs de recherche?

**Comment by Linkupdated** [comment]
1 champ qui recherche dans pas mal tous le texte en haut a coter du logo ou juste dans la section produits.

_Attendre la confirmation de @SimonLabbe_

**Comment by Linkupdated** [comment]
Système Terminé. Sa prit plus de temps que prévu vu que le système est très vieux.

Total: 3.5H
