### ISSUE TITLE
Mobile Henri Christof

### ISSUE THREAD

**Issue by SimonLabbe** [Linkupdated/Calypso#18]
Même mobile que Sonar

**Comment by Linkupdated** [comment]
cool!

**Comment by SimonLabbe** [comment]
Dès que tu est prêt!

Envoyé depuis un mobile

<div>-------- Message d'origine --------</div><div>De : Linkupdated notifications@github.com </div><div>Date :26/04/2015  04:49  (GMT-05:00) </div><div>À : Linkupdated/Calypso Calypso@noreply.github.com </div><div>Cc : SimonLabbe simon@labbe.ca </div><div>Objet : Re: [Calypso] Mobile Henri Christof (#18) </div><div>
</div>cool!

**Comment by Linkupdated** [comment]
C'est Fait, A Facturer 2.5H
