### ISSUE TITLE
Hmoquin - Regler les bug envoyer par le client

### ISSUE THREAD

**Issue by Linkupdated** [Linkupdated/Calypso#9]
Salut Simon, je t’avais appeler il y a quelque temps pour le projet Optométriste Granger Bernier qui n’apparait plus dans la section optométriste de notre site web. Il est présentement dans la section Clinique.

Merci de vérifié le tout et faire le correctif pour le remettre dans l’onglet Optométriste visible.

**Comment by Linkupdated** [comment]
**Voir section liquidation**
13-04-2015
Mobilier 19
Mobilier 20
Mobilier 21
La première photo est correcte mais les autres dans le même dossier sont allongé en largeur.

**Comment by Linkupdated** [comment]
contacter le client quand le travail sera terminé

**Comment by Linkupdated** [comment]
Terminé et client contacter

**Comment by Linkupdated** [comment]
Temps Total: .75

**Comment by SimonLabbe** [comment]
Un autre petit BUG
http://www.hmoquin.com/?page=nos-liquidations&cat=Fauteuil
La chaise 05 n'apparait pas.

les autres 09 - 15 - 22 c'est correct, c'est eux qui les ont enlevé

**Comment by SimonLabbe** [comment]
Encore un petit truc... quand on clic pour ajouter un produit usagé ça indique que le formulaire n'existe pas...

**Comment by Linkupdated** [comment]
fait!

**Comment by SimonLabbe** [comment]
http://hmoquin.com/?page=nos-promotions&cat=Accessoire
"Acessoire 01" a plusieurs photos et elles sont coupé à partir de la deuxième.

**Comment by Linkupdated** [comment]
Probleme resolut!
